name: Build_RDWHACK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos and ldid
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master $GITHUB_WORKSPACE/theos/sdks
          brew install ldid
        
      - name: Build Package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1
          
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: RDWHACK-Final
          path: packages/*.deb
